homepage:
    path:     /
    defaults: { _controller: SupermarketBundle:Default:index }

backend:
    path:     /backend
    defaults: { _controller: SupermarketBundle:Backend:index }

backend_valid:
    path:     /backend/valid
    defaults: { _controller: SupermarketBundle:Backend:valid }

backend_search_receipt:
    path:     /backend/search/receipt
    defaults: { _controller: SupermarketBundle:Backend:searchReceipt }

backend_search_user:
    path:     /backend/search/user
    defaults: { _controller: SupermarketBundle:Backend:searchUser }

backend_user:
    path:     /backend/users
    defaults: { _controller: SupermarketBundle:Backend:listUsers }

backend_receipt_edit:
    path:     /backend/receipt/edit/{id}
    defaults: { _controller: SupermarketBundle:Backend:editReceipt }

backend_user_receipts:
    path:     /backend/user/{id}
    defaults: { _controller: SupermarketBundle:Backend:getUserReceipts }

backend_increase:
    path:     /backend/receipt/increase
    defaults: { _controller: SupermarketBundle:Backend:increaseQuantity }

backend_download:
    path:     /backend/download/{id}
    defaults: { _controller: SupermarketBundle:Backend:generatePDF }

backend_receipt_form:
    path:     /backend/receipt/form/{id}
    defaults: { _controller: SupermarketBundle:Backend:getFormField }

category:
    path:     /category/{name}
    defaults: { _controller: SupermarketBundle:Articles:show }

single:
    path:     /single/{id}
    defaults: { _controller: SupermarketBundle:Articles:single }

contact:
    path:     /contact
    defaults: { _controller: SupermarketBundle:Default:contact }

checkout:
    path:     /checkout
    defaults: { _controller: SupermarketBundle:Cart:view }

checkout_confirm:
    path:     /checkout/pay
    defaults: { _controller: SupermarketBundle:Cart:pay }

checkout_pay:
    path:     /checkout/confirm
    defaults: { _controller: SupermarketBundle:Cart:confirm }

magasin:
    path:     /magasin
    defaults: { _controller: SupermarketBundle:Articles:allProducts}

search:
    path:     /search
    defaults: { _controller: SupermarketBundle:Articles:search}

cart_add:
    path:     /cart/add
    defaults: { _controller: SupermarketBundle:Cart:add}

cart_delete:
    path:     /cart/delete/{id}
    defaults: { _controller: SupermarketBundle:Cart:delete}

cart_update:
    path:     /cart/update/{id}/{number}
    defaults: { _controller: SupermarketBundle:Cart:update}

history:
    path:     /history
    defaults: { _controller: SupermarketBundle:Default:history}


